version: "3.8"

services:
  nginx:
    # environment:
    #   - NGINX_BASIC_AUTH_USER=${NGINX_BASIC_AUTH_USER}
    #   - NGINX_BASIC_AUTH_PASS=${NGINX_BASIC_AUTH_PASS}
    # env_file:
    #   - .env
    volumes:
      - "./scripts/docker/docker-entrypoint.sh:/usr/local/bin/docker-entrypoint.sh"
      - "./configs/nginx.conf:/etc/nginx/nginx.conf"
      - "./volumes/storage/nginx/configs/sites-enabled:/etc/nginx/sites-enabled"
      # - "./volumes/storage/nginx/ssl:/etc/nginx/ssl"
      - "./volumes/.vscode-server:/root/.vscode-server"
    # deploy:
    #   replicas: 0
    #   resources:
    #     limits:
    #       cpus: "1.0"
    #       memory: 1G
    # network_mode: bridge
    # ports:
    #   - "${NGINX_HTTPS_PORT:-443}:${NGINX_HTTPS_PORT:-443}"
    #   - "${NGINX_HTTP_PORT:-80}:${NGINX_HTTP_PORT:-80}"
    # command: ["--https=self"]
    # command: ["--https=valid"]
    # command: ["--https=lets"]
    # command: ["/bin/bash"]
