name: 3. Create Release

on:
  # workflow_run:
  #   workflows: ["2. Build and Publish"]
  #   types:
  #     - completed
  workflow_dispatch:

env:
  _WORKFLOW_STATE: active

jobs:
  create_release:
    name: Create Release
    runs-on: ubuntu-24.04
    permissions:
      contents: write
      actions: write
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Create release
        run: ./scripts/release.sh
      - name: Check Workflow
        run: |
          _WORKFLOW_STATE=$(gh api repos/$(gh repo view --json nameWithOwner -q .nameWithOwner)/actions/workflows/4.update-changelog.yml | jq -r '.state')
          echo "_WORKFLOW_STATE=${_WORKFLOW_STATE}" >> ${GITHUB_ENV}
      - name: Trigger Changelog
        if: ${{ env._WORKFLOW_STATE == 'active' }}
        run: gh workflow run 4.update-changelog.yml
